'use client'
import './globals.css'
import NavBar from '../components/NavBar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "next-themes"
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fellipe Tripovichy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ThemeProvider enableSystem={true} attribute='class'>
          <NavBar/>
          {children}
          <Footer/>
        </ThemeProvider>
        </body>
    </html>
  )
}
